version: "3.9"

services:
  app:
    build: .
    restart: on-failure
    depends_on:
      - redis
      - mongo
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      RD_DB: ${RD_DB:-5}
      RD_HOST: ${RD_HOST:-redis}
      RD_PORT: ${RD_PORT:-6379}
      MONGO_HOST: ${MONGO_HOST:-mongo}
      MONGO_PORT: ${MONGO_PORT:-27017}
      MONGO_USER: ${MONGO_USER:-admin}
      MONGO_PASS: ${MONGO_PASS:-admin}
    entrypoint:
      - ./bin/entrypoint.sh
  redis:
    image: redis:alpine
    restart: unless-stopped
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-admin}
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS:-admin}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER:-admin}:${MONGO_PASS:-admin}@${MONGO_HOST:-mongo}:${MONGO_PORT:-27017}/

volumes:
  mongo_db: