x-env: &env
  TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:?}
  MONGO_HOST: ${MONGO_HOST:-mongo}
  MONGO_PORT: ${MONGO_PORT:-27017}
  MONGO_USER: ${MONGO_USER:-admin}
  MONGO_PASS: ${MONGO_PASS:-admin}
  RD_DB: ${RD_DB:-5}
  RD_HOST: ${RD_HOST:-redis}
  RD_PORT: ${RD_PORT:-6379}

x-mongo-env: &mongoenv
  MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
  MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-admin}

services:
  app:
    build: .
    restart: on-failure
    depends_on:
      - redis
      - mongo
    environment:
      <<: *env
    entrypoint:
      - ./bin/entrypoint.sh
    ports:
      - "4400:4000"
    volumes:
      - ./logs:/app/logs
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - redis:/data
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"
    environment:
      <<: *mongoenv

volumes:
  mongo_db:
  redis:
