name: Bot

on: ["push"]

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12'
            - name: Install requirements
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Deploy to Heroku
              uses: akhileshns/heroku-deploy@v3.12.14
              with: 
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
                  heroku_email: ${{secrets.HEROKU_EMAIL}}